-- Ok, this is just same program in haskell, bt its designed to compare the output user provides to a verified answer.
--
-- In simplest case, I have a file and an answer I got verification from authors. Therefore I am sure my solution is correct. 
-- Now the case is to do this in a more authentic way
-- How to add a test to a Haskell app? This is more of a cabal question.
